remote_theme: sergiokopplin/indigo
name: Billy Ruffian
bio: 'On the Internet, nobody knows you're a warship'
picture: 'https://raw.githubusercontent.com/BillyRuffian/billyruffian.github.io/master/assets/images/Pug.png'
